=== nanomolina/xml_examples/ejercicio4/e4.dtd
<!ELEMENT bibliografía ( libro*, artículo* ) >
<!ELEMENT libro ( título, autor+, año, editor, lugar?, ISBN ) >
<!ELEMENT artículo ( título, autor+, revista, año, número, volumen, páginas? ) >
<!ELEMENT autor ( apellido+, nombre ) >
<!ELEMENT título ( #PCDATA ) >
<!ELEMENT año ( #PCDATA ) >
<!ELEMENT editor ( #PCDATA ) >
<!ELEMENT revista ( #PCDATA ) >
<!ELEMENT número ( #PCDATA ) >
<!ELEMENT volumen ( #PCDATA ) >
<!ELEMENT páginas ( #PCDATA ) >
<!ELEMENT apellido ( #PCDATA ) >
<!ELEMENT nombre ( #PCDATA ) >
<!ELEMENT lugar ( #PCDATA ) >
<!ELEMENT ISBN ( #PCDATA ) >

=== nanomolina/xml_examples/ejercicio4/e4.xml
<?xml version="1.0"?>
<!DOCTYPE bibliografía SYSTEM "e4.dtd">

<bibliografía>
    <libro>
        <título> Harry Potter y la piedra filosofal </título>
        <autor>
            <apellido> Downking </apellido>
            <nombre> Andrea </nombre>
        </autor>
        <año> 2001 </año>
        <editor> BRujas inc </editor>
        <lugar> Inglaterra </lugar>
        <ISBN> 18274 </ISBN>
    </libro>
    <libro>
        <título> Harry Potter y la camara secreta </título>
        <autor>
            <apellido> Downking </apellido>
            <nombre> Andrea </nombre>
        </autor>
        <año> 2002 </año>
        <editor> BRujas inc </editor>
        <lugar> Inglaterra </lugar>
        <ISBN> 18223454 </ISBN>
    </libro>
    <libro>
        <título> FAst and furious </título>
        <autor>
            <apellido> zabana </apellido>
            <nombre> joaquin </nombre>
        </autor>
        <año> 2005 </año>
        <editor> zafari inc </editor>
        <lugar> Brazil </lugar>
        <ISBN> 3473 </ISBN>
    </libro>
    <artículo>
        <título> harry y sus amigos </título>
        <autor>
            <apellido> Downking </apellido>
            <nombre> Andrea </nombre>
        </autor>
        <revista> MAGAZINE </revista>
        <año> 2001 </año>
        <número> 2 </número>
        <volumen> 1 </volumen>
        <páginas> 20 </páginas>
    </artículo>
</bibliografía>
