=== nanomolina/xml_examples/ejercicio1/e1.dtd
<!ELEMENT alumnos ( alumno* ) >
<!ELEMENT amigos ( universidad, alumno+ )+ >
<!ELEMENT alumno ( nombre, hijo*, materia* ) >
<!ELEMENT hijo ( nombre, cumpleaños ) >
<!ELEMENT cumpleaños ( día, mes, año ) >
<!ELEMENT materia ( nombre, examen* ) >
<!ELEMENT examen ( año, nota, universidad )+ >

<!ELEMENT universidad ( #PCDATA ) >
<!ELEMENT nombre ( #PCDATA ) >
<!ELEMENT día ( #PCDATA ) >
<!ELEMENT mes ( #PCDATA ) >
<!ELEMENT año ( #PCDATA ) >
<!ELEMENT nota ( #PCDATA ) >

<!ATTLIST materia tipo (terciario|grado|posgrado) "grado" >

=== nanomolina/xml_examples/ejercicio1/e1.xml
<?xml version="1.0"?>
<!DOCTYPE alumnos SYSTEM "e1.dtd">

<alumnos>
 <alumno>
  <nombre>Juan Perez</nombre>
  <hijo>
   <nombre>Luis Perez</nombre>
   <cumpleaños>
    <día>2</día>
    <mes>marzo</mes>
    <año>2001</año>
   </cumpleaños>
  </hijo>
  <materia tipo="grado">
   <nombre>Bases de datos</nombre>
   <examen>
    <año>2010</año>
    <nota>2</nota>
    <universidad>UNC</universidad>
   </examen>
   <examen>
    <año>2011</año>
    <nota>8</nota>
    <universidad>UNC</universidad>
   </examen>
  </materia>
 </alumno>
</alumnos>
