=== nanomolina/xml_examples/ejercicio3/e3.dtd
<!ELEMENT banco ( cuenta*, cliente*, impositor* ) >
<!ELEMENT cuenta ( numero-cuenta, nombre-sucursal, saldo ) >
<!ELEMENT cliente ( nombre-cliente, calle-cliente, ciudad-cliente ) >
<!ELEMENT impositor ( numero-cuenta, nombre-cliente ) >

<!ELEMENT numero-cuenta ( #PCDATA )>
<!ELEMENT nombre-sucursal ( #PCDATA )>
<!ELEMENT saldo ( #PCDATA )>
<!ELEMENT nombre-cliente ( #PCDATA )>
<!ELEMENT calle-cliente ( #PCDATA )>
<!ELEMENT ciudad-cliente ( #PCDATA )>

=== nanomolina/xml_examples/ejercicio3/e3.xml
<?xml version="1.0"?>
<!DOCTYPE banco SYSTEM "e3.dtd">

<banco>
	<cuenta>
		<numero-cuenta> C101 </numero-cuenta>
		<nombre-sucursal> Centro </nombre-sucursal>
		<saldo> 500 </saldo>
	</cuenta>
	<cuenta>
		<numero-cuenta> C102 </numero-cuenta>
		<nombre-sucursal> Navacerrada </nombre-sucursal>
		<saldo> 400 </saldo>
	</cuenta>
	<cuenta>
		<numero-cuenta> C201 </numero-cuenta>
		<nombre-sucursal> Galapagar </nombre-sucursal>
		<saldo> 900 </saldo>
	</cuenta>
	<cuenta>
		<numero-cuenta> C202 </numero-cuenta>
		<nombre-sucursal> Galapagar </nombre-sucursal>
		<saldo> 900 </saldo>
	</cuenta>
	<cliente>
		<nombre-cliente> González </nombre-cliente>
		<calle-cliente> Arenal </calle-cliente>
		<ciudad-cliente> La Granja </ciudad-cliente>
	</cliente>
	<cliente>
		<nombre-cliente> López </nombre-cliente>
		<calle-cliente> Mayor </calle-cliente>
		<ciudad-cliente> Córdoba </ciudad-cliente>
	</cliente>
	<impositor>
		<numero-cuenta> C101 </numero-cuenta>
		<nombre-cliente> González </nombre-cliente>
	</impositor>
	<impositor>
		<numero-cuenta> C201 </numero-cuenta>
		<nombre-cliente> González </nombre-cliente>
	</impositor>
	<impositor>
		<numero-cuenta> C102 </numero-cuenta>
		<nombre-cliente> López </nombre-cliente>
	</impositor>
</banco>
